version: '3'
services:
  springboottest:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    container_name: springboottest
    image: 192.168.56.104:5000/test_zsd/springboottest:0.0.3-SNAPSHOT
